import { defineSlotRecipe } from "@chakra-ui/react"
import { paginationAnatomy } from "@ark-ui/react/pagination"

export const paginationSlotRecipe = defineSlotRecipe({
    className: "chakra-pagination",
    slots: paginationAnatomy.keys(),
    base: {
        root: {
            display: "flex",
            alignItems: "center",
            gap: 1,
        },
        item: {
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            minW: 8,
            h: 8,
            px: 2,
            borderRadius: "md",
            fontSize: "sm",
            fontWeight: "medium",
            cursor: "pointer",
            border: "1px solid",
            borderColor: "gray.200",
            bg: "white",
            color: "gray.700",
            transition: "all 0.15s",
            _hover: {
                bg: "gray.50",
                borderColor: "gray.300",
            },
            _selected: {
                bg: "blue.500",
                borderColor: "blue.500",
                color: "white",
                _hover: {
                    bg: "blue.600",
                },
            },
            _disabled: {
                opacity: 0.4,
                cursor: "not-allowed",
                pointerEvents: "none",
            },
        },
        ellipsis: {
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            minW: 8,
            h: 8,
            px: 2,
            borderRadius: "md",
            fontSize: "sm",
            border: "1px solid",
            borderColor: "gray.200",
            bg: "white",
            color: "gray.500",
            cursor: "default",
            pointerEvents: "none",
        },
        prevTrigger: {
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            minW: 8,
            h: 8,
            px: 2,
            borderRadius: "md",
            fontSize: "sm",
            cursor: "pointer",
            border: "1px solid",
            borderColor: "gray.200",
            bg: "white",
            color: "gray.600",
            transition: "all 0.15s",
            _hover: {
                bg: "gray.50",
                borderColor: "gray.300",
            },
            _disabled: {
                opacity: 0.4,
                cursor: "not-allowed",
                pointerEvents: "none",
            },
        },
        nextTrigger: {
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            minW: 8,
            h: 8,
            px: 2,
            borderRadius: "md",
            fontSize: "sm",
            cursor: "pointer",
            border: "1px solid",
            borderColor: "gray.200",
            bg: "white",
            color: "gray.600",
            transition: "all 0.15s",
            _hover: {
                bg: "gray.50",
                borderColor: "gray.300",
            },
            _disabled: {
                opacity: 0.4,
                cursor: "not-allowed",
                pointerEvents: "none",
            },
        },
        firstTrigger: {
            display: "none",
        },
        lastTrigger: {
            display: "none",
        },
    },
})
