name: dsr-fe

services:
  app:
    image: iblcloud/searl-dsr-fe:1.0.0
    container_name: searl-dsr-fe
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://192.168.130.72:3014/api}
    ports:
      - "3013:3013"
