export enum ApiKey {
  saleSummary = 'saleSummary',
  coverDays = 'coverDays',
  coverDaysTotal = 'coverDaysTotal',
  forecastAccuracyMonthly = 'forecastAccuracyMonthly',
  forecastAccuracyYearly = 'forecastAccuracyYearly',
  inventoryDays = 'inventoryDays',
  aboveBelowThreshold = 'aboveBelowThreshold',
  forecastAccuracyCategoryMonthly = 'forecastAccuracyCategoryMonthly',
  forecastAccuracyCategoryYearly = 'forecastAccuracyCategoryYearly',
  iblVsTscl = 'iblVsTscl',
  totalSku = 'totalSku',
  dispatchVsOrder = 'dispatchVsOrder',
  serviceMeasure = 'serviceMeasure',
  tgtVsActual = 'tgtVsActual',
  filters = 'filters',
  rpm = 'rpm',
  wip = 'wip',
}
