export enum ApiKey {
  sales = 'sales',
  filters = 'filters',
  saleSummary = 'saleSummary',
  dailySalesAvg = 'dailySalesAvg',
  mtdSalesDetail = 'mtdSalesDetail',
  perDaySales = 'perDaySales',
  saleGrowthNational = 'saleGrowthNational',
  saleGrowthNationalTable = 'saleGrowthNationalTable',
  productInventoryAvailable = 'productInventoryAvailable',
  productInventoryRequired = 'productInventoryRequired',
  saleSummaryTotal = 'saleSummaryTotal',
  salesBranchWise = 'salesBranchWise',
  salesBranchWiseTable = 'salesBranchWiseTable',
  salesAchievements = 'salesAchievements',
  salesAchievementsTotal = 'salesAchievementsTotal',
  productInventoryVsTarget = 'productInventoryVsTarget',
  productInventoryBranchWise = 'productInventoryBranchWise',
  rdSalesDetail = 'rdSalesDetail',
  rdSalesGrowth = 'rdSalesGrowth',
}
